kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.microservice.name }}-persistent-volume-claim
  namespace: {{ .Values.microservice.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.microservice.namespace }}
    app.kubernetes.io/component: persistent-volume-claim
    app.kubernetes.io/instance: {{ .Values.microservice.name }}-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.workload.storageCapacity }}