apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}-secret
  namespace: {{ .Values.microservice.namespace }}
type: Opaque
data:
    POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD | quote }}