apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kubernetes-experiments-01
  labels:
    app.kubernetes.io/name: kubernetes-experiments-01
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: postgres-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432