kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-persistent-volume-claim
  namespace: kubernetes-experiments-01
  labels:
    app.kubernetes.io/name: kubernetes-experiments-01
    app.kubernetes.io/component: persistent-volume-claim
    app.kubernetes.io/instance: postgres-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi