kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-persistent-volume
  namespace: kubernetes-experiments-01
  labels:
    type: local
    app.kubernetes.io/name: kubernetes-experiments-01
    app.kubernetes.io/component: persistent-volume
    app.kubernetes.io/instance: postgres-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"