apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kubernetes-experiments-01
spec:
  serviceName: postgres
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kubernetes-experiments-01
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-configmap
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-persistent-storage
  volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
#      volumes:
#        - name: postgresdb
#          persistentVolumeClaim:
#            claimName: postgres-pv-claim