microservice: ## general service details
  name: kubernetes-experiments-01-portal
  namespace: kubernetes-experiments-01
  replicas: 2

workload: ## container specific configurations
  image: cebartling/k8s-experiments-01-portal
  port: 3000
  targetPort: 3000
  resources:
    memory: "1024Mi"
    cpu: "200m"
  livenessDelay: 15
  livenessPeriod: 15
  readinessDelay: 15
  readinessPeriod: 15

env: ## environment variables
  API_SERVER_URL: http://kubernetes-experiments-01-api-server:3000

secrets: ## base64-encoded secrets


